
//
// table for mixamo/rpm to vrm
//

export const Mixamo2VRM = {
	Hips: 'hips',
	Spine: 'spine',
	Spine1: 'chest',
	Spine2: 'upperChest', // @todo reallusion uses CC_Base_Spine01 - may want to study this closer
	Neck: 'neck',
	Head: 'head',
	LeftShoulder: 'leftShoulder',
	LeftArm: 'leftUpperArm',
	LeftForeArm: 'leftLowerArm',
	LeftHand: 'leftHand',
	LeftHandThumb1: 'leftThumbMetacarpal',
	LeftHandThumb2: 'leftThumbProximal',
	LeftHandThumb3: 'leftThumbDistal',
	LeftHandIndex1: 'leftIndexProximal',
	LeftHandIndex2: 'leftIndexIntermediate',
	LeftHandIndex3: 'leftIndexDistal',
	LeftHandMiddle1: 'leftMiddleProximal',
	LeftHandMiddle2: 'leftMiddleIntermediate',
	LeftHandMiddle3: 'leftMiddleDistal',
	LeftHandRing1: 'leftRingProximal',
	LeftHandRing2: 'leftRingIntermediate',
	LeftHandRing3: 'leftRingDistal',
	LeftHandPinky1: 'leftLittleProximal',
	LeftHandPinky2: 'leftLittleIntermediate',
	LeftHandPinky3: 'leftLittleDistal',
	RightShoulder: 'rightShoulder',
	RightArm: 'rightUpperArm',
	RightForeArm: 'rightLowerArm',
	RightHand: 'rightHand',
	RightHandPinky1: 'rightLittleProximal',
	RightHandPinky2: 'rightLittleIntermediate',
	RightHandPinky3: 'rightLittleDistal',
	RightHandRing1: 'rightRingProximal',
	RightHandRing2: 'rightRingIntermediate',
	RightHandRing3: 'rightRingDistal',
	RightHandMiddle1: 'rightMiddleProximal',
	RightHandMiddle2: 'rightMiddleIntermediate',
	RightHandMiddle3: 'rightMiddleDistal',
	RightHandIndex1: 'rightIndexProximal',
	RightHandIndex2: 'rightIndexIntermediate',
	RightHandIndex3: 'rightIndexDistal',
	RightHandThumb1: 'rightThumbMetacarpal',
	RightHandThumb2: 'rightThumbProximal',
	RightHandThumb3: 'rightThumbDistal',
	LeftUpLeg: 'leftUpperLeg',
	LeftLeg: 'leftLowerLeg',
	LeftFoot: 'leftFoot',
	LeftToeBase: 'leftToes',
	RightUpLeg: 'rightUpperLeg',
	RightLeg: 'rightLowerLeg',
	RightFoot: 'rightFoot',
	RightToeBase: 'rightToes'
}
