
///
/// convenience table to map vrms to rpm - our system uses rpm / mixamo style rigs
///
/// https://www.aicgworld.com/qinweining/cc_blender_tools/-/blob/c0d8d25e972bd3006feb763b9557072402ac5391/rigify_mapping_data.py
///

export const VRM2Mixamo = {
//    'RL_BoneRoot' : 'Armature',
  'hips' : 'Hips',
  'spine' : 'Spine',
  'chest' : 'Spine1',
  'upperChest' : 'Spine2',
  'neck' : 'Neck',
  'head' : 'Head',
  'leftEye' : 'LeftEye',
  'rightEye' : 'RightEye',
//    'jaw' : null,
  'leftUpperLeg' : 'LeftUpLeg',
  'leftLowerLeg' : 'LeftLeg',
  'leftFoot' : 'LeftFoot',
  'leftToes' : 'LeftToeBase',
  'rightUpperLeg' : 'RightUpLeg',
  'rightLowerLeg' : 'RightLeg',
  'rightFoot' : 'RightFoot',
  'rightToes' : 'RightToeBase',
  'leftShoulder' : 'LeftShoulder',
  'leftUpperArm' : 'LeftArm',
  'leftLowerArm' : 'LeftForeArm',
  'leftHand' : 'LeftHand',
  'rightShoulder' : 'RightShoulder',
  'rightUpperArm' : 'RightArm',
  'rightLowerArm' : 'RightForeArm',
  'rightHand' : 'RightHand',
  'leftThumbMetacarpal' : 'LeftHandThumb1',
  'leftThumbProximal' : 'LeftHandThumb2',
  'leftThumbDistal' : 'LeftHandThumb3',
  'leftIndexProximal' : 'LeftHandIndex1',
  'leftIndexIntermediate' : 'LeftHandIndex2',
  'leftIndexDistal' : 'LeftHandIndex3',
  'leftMiddleProximal' : 'LeftHandMiddle1',
  'leftMiddleIntermediate' : 'LeftHandMiddle2',
  'leftMiddleDistal' : 'LeftHandMiddle3',
  'leftRingProximal' : 'LeftHandRing1',
  'leftRingIntermediate' : 'LeftHandRing2' ,
  'leftRingDistal' : 'LeftHandRing3',
  'leftLittleProximal' : 'LeftHandPinky1',
  'leftLittleIntermediate' : 'LeftHandPinky2',
  'leftLittleDistal' : 'LeftHandPinky3',
  'rightThumbMetacarpal' : 'RightHandThumb1',
  'rightThumbProximal' : 'RightHandThumb2',
  'rightThumbDistal' : 'RightHandThumb3',
  'rightIndexProximal' : 'RightHandIndex1',
  'rightIndexIntermediate' : 'RightHandIndex2',
  'rightIndexDistal' : 'RightHandIndex3',
  'rightMiddleProximal' : 'RightHandMiddle1',
  'rightMiddleIntermediate' : 'RightHandMiddle2',
  'rightMiddleDistal' : 'RightHandMiddle3',
  'rightRingProximal' : 'RightHandRing1',
  'rightRingIntermediate' : 'RightHandRing2' ,
  'rightRingDistal' : 'RightHandRing3',
  'rightLittleProximal' : 'RightHandPinky1',
  'rightLittleIntermediate' : 'RightHandPinky2',
  'rightLittleDistal' : 'RightHandPinky3',
}
